on:
  workflow_call:
    inputs:
      build-context:
        required: true
        type: string
      dockerfile-name:
        required: true
        type: string
      image-name:
        required: true
        type: string 
      image-type:
        required: true
        type: string 
      image-system:
        required: true
        type: string

jobs:
  build_and_push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ${{ inputs.build-context }}/${{ inputs.dockerfile-name }}
            context: ${{ inputs.build-context }}
            image: pfaffk/${{ inputs.image-name }}
            tags: |
              type=raw,value=${{ inputs.image-type }}-${{ inputs.image-system }}
              type=raw,value=${{ inputs.image-type }}-${{ inputs.image-system }}-{{date 'YYYYMMDD'}}
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
     
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ matrix.image }}
          labels: |
            maintainer=Kamil Pfaff
            org.opencontainers.image.title=${{ inputs.image-system }}-${{ inputs.image-name }}
          tags: ${{ matrix.tags }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
