name: Build and publish ALL docker images.

on: 
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * 1' # Build every monday at 20:00

jobs:
  build_nginx_images:
    uses: ./.github/workflows/build-nginx.yml
    secrets: inherit
  
  build_node_images:
    uses: ./.github/workflows/build-node.yml
    secrets: inherit

  build_php_images:
    uses: ./.github/workflows/build-php.yml
    secrets: inherit
